#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "librex"
name = "LibreX"
description.en = "Meta search engine for Google and popular torrent sites"
description.fr = "Méta moteur de recherche pour Google et les sites torrent populaires"

version = "2023.11.14~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
demo = "https://librey.devol.it/"
admindoc = "https://github.com/hnhx/librex/wiki"
code = "https://github.com/hnhx/librex"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/hnhx/librex/archive/b5a9f12df91cb8ded541df291da58ce2f104fe62.tar.gz"
    sha256 = "b88ae9896b281f2929b4e48f947d261bb7ecd7e2c6bd5c378237be3606f6c9b5"
    autoupdate.upstream = "https://github.com/hnhx/librex"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-dom, php8.2-curl"
