packaging_format = 2

id = "librex"
name = "LibreX"
description.en = "Meta search engine for Google and popular torrent sites"
description.fr = "Méta moteur de recherche pour Google et les sites torrent populaires"

version = "2023.06.16~ynh3"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
demo = "https://librex.beparanoid.de"
admindoc = "https://github.com/hnhx/librex/wiki"
code = "https://github.com/hnhx/librex"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/hnhx/librex/archive/a75a233fbdc34429f93a230bb724bab472ce622f.tar.gz"
        sha256 = "749f9ff224f7f922ab86843438c1fc42845c8ca22e637734f6b10911f992b503"
        autoupdate.upstream = "https://github.com/hnhx/librex"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-dom php8.2-curl"
