packaging_format = 2

id = "librex"
name = "LibreX"
description.en = "Meta search engine for Google and popular torrent sites"
description.fr = "Méta moteur de recherche pour Google et les sites torrent populaires"

version = "20221217~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://github.com/hnhx/librex"
demo = "https://librex.beparanoid.de"
admindoc = "https://github.com/hnhx/librex/wiki"
code = "https://github.com/hnhx/librex"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/hnhx/librex/archive/f883df2d07dfb6b4514e723e545399bb1d2ddcca.tar.gz"
        sha256 = "00e42002519d3b2035425981a39b8b607a9f3cc30784e8679ce93e8f9639ac30"
        autoupdate.upstream = "https://github.com/hnhx/librex"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php7.4-dom php7.4-curl"
    